name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ldid
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential libplist-dev libssl-dev openssl qemu-user-binfmt
          cd /tmp
          git clone git://git.saurik.com/ldid.git
          cd ldid
          git submodule update --init
          gcc -I. -c -o lookup2.o lookup2.c
          g++ -std=c++11 -o ldid lookup2.o ldid.cpp -I. -lcrypto -lplist -lxml2
          sudo mv ldid /usr/local/bin
      - name: install pnpm and npm
        run: |
          curl -L https://get.pnpm.io/v6.js | node - add --global pnpm@next npm@7
      - name: pnpm install
        run: pnpm install
      - name: Publish Packages
        if: false
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm release
      - name: Copy Artifacts
        run: pnpm run copy-artifacts
      - name: Generate release description
        run: pnpm run make-release-description
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/*
          body_path: RELEASE.md
